---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cleansing-service"
  namespace: "default"
  labels:
    app: "cleansing-service"
    version: "v1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "cleansing-service"
  template:
    metadata:
      labels:
        app: "cleansing-service"
        version: "v1"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      # Security context para pod
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532  # nonroot user
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
        
      containers:
      - name: "cleansing-service"
        # Usar imagen específica con tag (no latest)
        image: "gcr.io/PROJECT_ID/cleansing:v1.0.0"
        imagePullPolicy: Always
        
        # Security context para container
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
          capabilities:
            drop:
              - ALL
        
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        # Resource limits
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        
        # Environment variables
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: JAVA_OPTS
          value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
        
        # Volumes montados como tmpfs (temporal, en memoria)
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: tmp-cache
          mountPath: /var/cache
        
      volumes:
      - name: tmp
        emptyDir: {}
      - name: tmp-cache
        emptyDir: {}
      
      # Pod disruption budget
      terminationGracePeriodSeconds: 30
      
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "cleansing-service"
  namespace: "default"
  labels:
    app: "cleansing-service"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: "cleansing-service"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "cleansing-service-hpa"
  namespace: "default"
  labels:
    app: "cleansing-service"
spec:
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "cleansing-service"
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 70
  - type: "Resource"
    resource:
      name: "memory"
      target:
        type: "Utilization"
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: "Percent"
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: "Percent"
        value: 100
        periodSeconds: 30
      - type: "Pods"
        value: 2
        periodSeconds: 30
      selectPolicy: Max
